"""yente-client: Python SDK for the yente / OpenSanctions matching API.

Top-level re-exports cover the canonical surface — pull the per-schema entity
classes either as ``from yente_client import Person, Company`` or
``from yente_client.entities import Person, Company``.
"""

from __future__ import annotations

from .async_client import AsyncClient
from .client import BEST_ALGORITHM, Client

# Re-export every per-schema entity class (Person, Company, Vessel, ...).
# entities/__init__.py is generated by scripts/regen_model.py and carries an
# `__all__` listing all 69 schema classes; star-import picks them all up.
from .entities import *  # noqa: F401, F403
from .entities import EntityInput
from .entities import __all__ as _entities_all
from .exceptions import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConfigurationError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TransportError,
    YenteError,
)
from .filters import MatchFilters, SearchFilters
from .models import (
    AdjacentPropertyResponse,
    AdjacentResponse,
    Algorithm,
    AlgorithmsResponse,
    CatalogResponse,
    Dataset,
    Entity,
    FeatureResult,
    MatchResponse,
    ScoredEntity,
    SearchFacet,
    SearchFacetItem,
    SearchResponse,
    StatusResponse,
    TotalSpec,
)

__all__ = [
    # Constants
    "BEST_ALGORITHM",
    # Client
    "AsyncClient",
    "Client",
    # Entity input types
    "EntityInput",
    # Filters
    "MatchFilters",
    "SearchFilters",
    # Response models
    "AdjacentPropertyResponse",
    "AdjacentResponse",
    "Algorithm",
    "AlgorithmsResponse",
    "CatalogResponse",
    "Dataset",
    "Entity",
    "FeatureResult",
    "MatchResponse",
    "ScoredEntity",
    "SearchFacet",
    "SearchFacetItem",
    "SearchResponse",
    "StatusResponse",
    "TotalSpec",
    # Exceptions
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "ConfigurationError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "TransportError",
    "YenteError",
    # Per-schema entity classes (Person, Company, …) via entities/__init__.py
    *_entities_all,
]
