"""Entity input classes.

This module is regenerated by ``scripts/regen_model.py`` once codegen lands
in Phase D — at that point it will re-export every per-schema class
(``Person``, ``Company``, …). For now it surfaces only the base types.
"""

from ._base import EntityInput, _EntityBase

__all__ = ["EntityInput", "_EntityBase"]
